### Send POST request with User json body
POST http://localhost:10000/userLogin/addUser
Content-Type: application/json

{
  "username": "user",
  "password": "user",
  "role": "user"
}

### GET request with User info
GET http://localhost:10000/userLogin/getUser?username=user
Accept: application/json

## 场景: 使用user用户登录，可以访问 /userLogin/user接口，不能访问/userLogin/admin接口
### GET request with User info
GET http://localhost:10000/userLogin/user
Accept: application/json

### GET request with User info
GET http://localhost:10000/userLogin/admin
Accept: application/json